export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  courses: '/courses',
  courseNew: '/courses/new',
  courseDetail: (id: number | string) => `/courses/${id}`,
  courseEdit: (id: number | string) => `/courses/${id}/edit`,
  myCourses: '/teaching',
  tutors: '/tutors',
  tutorDetail: (id: number | string) => `/tutors/${id}`,
  tutorEditMe: '/tutor-profile/edit',
  me: '/profile',
  meEdit: '/profile/edit',
  applyTutor: '/become-a-tutor',
  enrollments: '/enrollments',
  enrollmentDetail: (id: number | string) => `/enrollments/${id}`,
  myEnrollments: '/learning',
  adminApplications: '/admin/tutor-applications',
  myRequests: '/requests',
  tutorInbox: '/inbox',
  adminRequests: '/admin/tutoring-requests',
  mySection: '/dashboard',
  adminSection: '/admin',
} as const
