export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  tutors: '/tutors',
  tutorDetail: (id: number | string) => `/tutors/${id}`,
  tutorEditMe: '/tutor-profile/edit',
  me: '/profile',
  meEdit: '/profile/edit',
  applyTutor: '/become-a-tutor',
  adminApplications: '/admin/tutor-applications',
  myRequests: '/requests',
  tutorInbox: '/inbox',
  adminRequests: '/admin/tutoring-requests',
  mySection: '/dashboard',
  adminSection: '/admin',
} as const
